name: Deploy Keeper Mainnet

on:
  push:
    branches:
      - main
    paths:
      - "keeper/**"
      - ".github/workflows/deploy-keeper-mainnet.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: keeper
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly mainnet app
        run: flyctl deploy -c fly.mainnet.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
